# Generated by Django 2.1 on 2018-08-27 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pronunciation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.CharField(max_length=250, verbose_name='Произношение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Используется')),
            ],
            options={
                'verbose_name_plural': 'Произношения',
                'verbose_name': 'Произношение',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Слово')),
                ('meaning', models.TextField(verbose_name='Значение')),
                ('spelling', models.CharField(max_length=250, verbose_name='Транскрипция')),
                ('raw_od_article', models.TextField(verbose_name='Сырые данные с OD')),
            ],
            options={
                'verbose_name_plural': 'Слова',
                'verbose_name': 'Слово',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='WordLearningState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_user_know_meaning', models.BooleanField(default=False, verbose_name='Выучил значение')),
                ('is_user_know_pronunciation', models.BooleanField(default=False, verbose_name='Выучил произношение')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Количество показов')),
                ('last_usage_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего показа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Word', verbose_name='Слово')),
            ],
            options={
                'verbose_name_plural': 'Статистика',
                'verbose_name': 'Статистика',
            },
        ),
        migrations.AddField(
            model_name='pronunciation',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Word', verbose_name='Слово'),
        ),
    ]
