# Generated by Django 2.1 on 2018-08-27 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Значение')),
            ],
            options={
                'verbose_name_plural': 'Доп. значения',
                'verbose_name': 'Доп. значение',
            },
        ),
        migrations.RenameField(
            model_name='word',
            old_name='meaning',
            new_name='general_meaning',
        ),
        migrations.AddField(
            model_name='meaning',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Word', verbose_name='Слово'),
        ),
    ]
