# Generated by Django 2.1 on 2018-08-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20180827_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronunciation',
            name='audio',
            field=models.FileField(upload_to='audio', verbose_name='Произношение'),
        ),
    ]
