# Generated by Django 2.1 on 2018-08-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20180827_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='meaning',
            name='raw_od_data',
            field=models.TextField(blank=True, null=True, verbose_name='Сырые данные с OD'),
        ),
        migrations.AlterField(
            model_name='pronunciation',
            name='audio',
            field=models.FileField(upload_to='media/audio', verbose_name='Произношение'),
        ),
    ]
