# Generated by Django 2.1 on 2018-09-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_auto_20180831_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meaning',
            name='raw_od_data',
        ),
        migrations.AddField(
            model_name='pronunciation',
            name='raw_od_data',
            field=models.TextField(blank=True, null=True, verbose_name='Сырые данные с OD'),
        ),
    ]
