# Generated by Django 2.1 on 2018-09-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_auto_20180905_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='general_meaning',
        ),
    ]
