# Generated by Django 2.1 on 2018-09-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_remove_word_general_meaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Используется'),
        ),
    ]
