# Generated by Django 2.1 on 2018-09-19 15:03

from django.db import migrations
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_wordlearningstate_preferred_pronunciation'),
    ]

    operations = [
        migrations.AddField(
            model_name='meaning',
            name='examples',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True),
        ),
    ]
