# Generated by Django 2.1 on 2018-10-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0011_auto_20180924_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlearningstate',
            name='training_session',
            field=models.BooleanField(default=False, verbose_name='Сеанс обучения'),
        ),
    ]
